# Generated by Django 3.2.4 on 2022-02-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multimedia',
            name='galery',
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, to='strona.Tags'),
        ),
    ]
