# Generated by Django 4.0.2 on 2022-04-25 18:47

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0002_auto_20220224_0030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AddField(
            model_name='multimedia',
            name='image_ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='photos',
            field=versatileimagefield.fields.VersatileImageField(upload_to='photos/', verbose_name='Image'),
        ),
    ]
