# Generated by Django 4.0 on 2022-05-20 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0002_members_alter_post_tag_multimedia_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimedia',
            name='members',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_photo', to='strona.members'),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='strona.post'),
        ),
    ]
