# Generated by Django 4.0 on 2022-05-20 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0003_alter_multimedia_members_alter_multimedia_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='email',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
