# Generated by Django 4.0 on 2022-06-12 13:21

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0004_members_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='event',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='members',
            name='email',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='photos',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='photos/', verbose_name='Image'),
        ),
    ]
